# Generated by Django 2.1.1 on 2018-09-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_auth', models.CharField(blank=True, max_length=50)),
                ('comment_authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('auth', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='cover')),
                ('read_time', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
