# Generated by Django 2.0.4 on 2018-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_comment_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_auth',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
