# Generated by Django 2.0.4 on 2018-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180730_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
